import type { MeetingSummary } from "@/types";

export function formatAsText(summary: MeetingSummary): string {
  const lines: string[] = [];

  lines.push(summary.title.toUpperCase());
  lines.push(`Date: ${new Date(summary.date).toLocaleDateString()} | Duration: ${summary.duration} | Speakers: ${summary.speakers.join(", ")}`);
  lines.push("");

  lines.push("OVERVIEW");
  lines.push(summary.executiveSummary);
  lines.push("");

  if (summary.keyTakeaways.length > 0) {
    lines.push("KEY TAKEAWAYS");
    summary.keyTakeaways.forEach((t) => lines.push(`  - ${t}`));
    lines.push("");
  }

  if (summary.detailedPoints.length > 0) {
    lines.push("DISCUSSION POINTS");
    summary.detailedPoints.forEach((dp) => {
      lines.push(`  ${dp.topic}`);
      if (dp.speakers.length > 0) lines.push(`    Contributors: ${dp.speakers.join(", ")}`);
      dp.points.forEach((p) => lines.push(`    - ${p}`));
      lines.push("");
    });
  }

  if (summary.actionItems.length > 0) {
    lines.push("ACTION ITEMS");
    summary.actionItems.forEach((item) => {
      const parts = [`  [ ] ${item.task}`];
      if (item.assignee) parts.push(`      Assignee: ${item.assignee}`);
      if (item.deadline) parts.push(`      Deadline: ${item.deadline}`);
      parts.push(`      Priority: ${item.priority}`);
      lines.push(parts.join("\n"));
    });
    lines.push("");
  }

  return lines.join("\n");
}

export function formatAsHtml(summary: MeetingSummary): string {
  const sections: string[] = [];

  sections.push(`
    <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 640px; margin: 0 auto; color: #111827;">
      <h1 style="font-size: 24px; margin-bottom: 4px;">${esc(summary.title)}</h1>
      <p style="color: #6b7280; font-size: 14px; margin-top: 0;">
        ${new Date(summary.date).toLocaleDateString()} &middot; ${esc(summary.duration)} &middot; ${summary.speakers.map(esc).join(", ")}
      </p>
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 16px 0;" />
  `);

  sections.push(`
      <h2 style="font-size: 16px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Overview</h2>
      <p style="line-height: 1.6;">${esc(summary.executiveSummary)}</p>
  `);

  if (summary.keyTakeaways.length > 0) {
    sections.push(`
      <h2 style="font-size: 16px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Key Takeaways</h2>
      <ul style="padding-left: 20px; line-height: 1.8;">
        ${summary.keyTakeaways.map((t) => `<li>${esc(t)}</li>`).join("")}
      </ul>
    `);
  }

  if (summary.detailedPoints.length > 0) {
    sections.push(`
      <h2 style="font-size: 16px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Discussion Points</h2>
    `);
    summary.detailedPoints.forEach((dp) => {
      sections.push(`
        <h3 style="font-size: 15px; margin-bottom: 4px;">${esc(dp.topic)}</h3>
        ${dp.speakers.length > 0 ? `<p style="font-size: 12px; color: #9ca3af; margin-top: 0;">Contributors: ${dp.speakers.map(esc).join(", ")}</p>` : ""}
        <ul style="padding-left: 20px; line-height: 1.6;">
          ${dp.points.map((p) => `<li style="font-size: 14px; color: #4b5563;">${esc(p)}</li>`).join("")}
        </ul>
      `);
    });
  }

  if (summary.actionItems.length > 0) {
    sections.push(`
      <h2 style="font-size: 16px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.05em;">Action Items</h2>
      <table style="width: 100%; border-collapse: collapse; font-size: 14px;">
        <thead>
          <tr style="border-bottom: 2px solid #e5e7eb; text-align: left;">
            <th style="padding: 8px 12px;">Task</th>
            <th style="padding: 8px 12px;">Assignee</th>
            <th style="padding: 8px 12px;">Priority</th>
          </tr>
        </thead>
        <tbody>
          ${summary.actionItems
            .map(
              (item) => `
            <tr style="border-bottom: 1px solid #f3f4f6;">
              <td style="padding: 8px 12px;">${esc(item.task)}</td>
              <td style="padding: 8px 12px; color: #6b7280;">${esc(item.assignee || "—")}</td>
              <td style="padding: 8px 12px;">
                <span style="display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: 500; background: ${
                  item.priority === "high" ? "#fef2f2; color: #dc2626" : item.priority === "medium" ? "#fffbeb; color: #d97706" : "#f0fdf4; color: #16a34a"
                };">${item.priority}</span>
              </td>
            </tr>`
            )
            .join("")}
        </tbody>
      </table>
    `);
  }

  sections.push(`
      <hr style="border: none; border-top: 1px solid #e5e7eb; margin: 24px 0 12px;" />
      <p style="font-size: 12px; color: #9ca3af; text-align: center;">Generated by Meeting Summarizer</p>
    </div>
  `);

  return sections.join("");
}

function esc(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
